file(MAKE_DIRECTORY "${OUTPUT}")
execute_process(COMMAND "${PROGRAM}" "${OUTPUT}" RESULT_VARIABLE result OUTPUT_VARIABLE log ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Export exited ${result}: ${error} ${log}")
endif()
foreach(name contour_first.tsv contour_second.tsv)
  execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${OUTPUT}/${name}" "${REFERENCE}/${name}" RESULT_VARIABLE different)
  if(different)
    message(FATAL_ERROR "Frozen historical export differs: ${name}")
  endif()
endforeach()
