if(NOT DEFINED WORKERS)
  set(WORKERS 0)
endif()
execute_process(COMMAND "${PROGRAM}" "${OUTPUT}" "${MODE}" "${WORKERS}" 0 RESULT_VARIABLE result OUTPUT_VARIABLE log ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "M1 characterization failed: ${result} ${error} ${log}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${OUTPUT}" "${REFERENCE}" RESULT_VARIABLE different)
if(different)
  message(FATAL_ERROR "M1 frozen historical reference differs: ${OUTPUT}")
endif()
