execute_process(COMMAND "${PROGRAM}" "${OUTPUT}" 600 "${MASK}" RESULT_VARIABLE result OUTPUT_VARIABLE log ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Differential failed: ${result} ${error} ${log}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E compare_files "${OUTPUT}" "${REFERENCE}" RESULT_VARIABLE different)
if(different)
  message(FATAL_ERROR "STOP: randomized differential differs from historical oracle")
endif()
