file(SHA256 "${REFERENCE}" expected)
file(WRITE "${OUTPUT}/m1-stress-hashes.tsv" "workers\trun\tsha256\n")
foreach(workers 1 2 3 4 6 8)
  foreach(run RANGE 1 20)
    set(record "${OUTPUT}/m1-stress-${workers}-${run}.tsv")
    execute_process(COMMAND "${PROGRAM}" "${record}" small "${workers}" 1 RESULT_VARIABLE result OUTPUT_VARIABLE log ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "M1 stress run failed: ${error} ${log}")
    endif()
    file(SHA256 "${record}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "STOP: M1 stress mismatch at ${workers}/${run}")
    endif()
    file(APPEND "${OUTPUT}/m1-stress-hashes.tsv" "${workers}\t${run}\t${actual}\n")
  endforeach()
endforeach()
