file(SHA256 "${REFERENCE}" expected)
file(WRITE "${OUTPUT}/stress-hashes.tsv" "workers\trun\tsha256\n")
foreach(workers 1 2 4 8)
  foreach(run RANGE 1 20)
    set(record "${OUTPUT}/stress-${workers}-${run}.tsv")
    execute_process(COMMAND "${PROGRAM}" "${record}" "${workers}" perturb
      RESULT_VARIABLE result OUTPUT_VARIABLE log ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "Stress run failed: workers=${workers}, run=${run}: ${error} ${log}")
    endif()
    file(SHA256 "${record}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "STOP: stress output differs from frozen oracle: workers=${workers}, run=${run}")
    endif()
    file(APPEND "${OUTPUT}/stress-hashes.tsv" "${workers}\t${run}\t${actual}\n")
  endforeach()
endforeach()
